dbs:
    GENCODEv27:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: True
    GENCODEv27_sabido:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
            - res/data/seq/sabido/Human.DeNovo.protein
        tax: human
        enabled: True
        add_confidence:
            -
                neg: True
                column: 'protein id'
                strings: ["ENS","sp\\|","KKA1_ECOLX"]
    GENCODEv24:
        paths: 
            - res/data/seq/gencode/gencode.v24.pc_translations.NoRT.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False

datasets:
    sabido:
        enabled: True
        dbs:
            - GENCODEv27
            - GENCODEv27_sabido
        groupings:
            single: 'os.path.splitext(x)[0]'
            byrep: '"_".join(x.split("_")[0:4])'
    wei_2016:
        urls:
            pub: https://pubs.acs.org/doi/10.1021/acs.jproteome.6b00390
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD004092
        enabled: False
        dbs:
            - GENCODEv27
        groupings:
            single: 'os.path.splitext(x)[0]'
    kim_2014:
        enabled: True
        dbs:
            - GENCODEv27
        urls:
            pub: https://www.nature.com/articles/nature13302
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD000561
        groupings:
            single: 'os.path.splitext(x)[0]'
            tissue: '"_".join(x.split("_")[0:2])'

software:
    search:
        comet:
            bin: bin/comet/comet.2017013.linux.exe
            params: res/conf/comet/comet.params.{ds}.conf
            threads: 4
            enabled: True
        xtandem:
            bin: bin/xtandem/bin/tandem.exe
            params: res/conf/xtandem/xtandem.params.{ds}.xml
            threads: 4
            enabled: False
    assign-confidence:
        methods:
            - tdc
            - mix-max
