dbs:
    GENCODEvM27:
        paths:
            crud: res/data/seq/crud/crud.fasta.gz
            gencode: res/data/seq/gencode/gencode.vM27.pc_translations.fa.gz
        tax: mouse
        enabled: True
    GENCODEv36:
        paths:
            crud: res/data/seq/crud/crud.fasta.gz
            gencode: res/data/seq/gencode/gencode.v36.pc_translations.fa.gz
            ncx: res/data/seq/ncx/NCX_20210225.fa.gz
        tax: human
        enabled: False
    GENCODEv33_20200420:
        paths:
            crud: res/data/seq/crud/crud.fasta
            gencode: res/data/seq/gencode/gencode.v33.pc_translations.fa
            ncx: res/data/seq/ncx/NC-xcheck.fa
        tax: human
        enabled: False
    GENCODEv33:
        paths:
            crud: res/data/seq/crud/crud.fasta
            gencode: res/data/seq/gencode/gencode.v33.pc_translations.fa
        tax: human
        enabled: False
    GUR:
        paths:
            crap: res/data/seq/crap/crap.fasta
            gencode: res/data/seq/gencode/gencode.v29.pc_translations.fa
            uniprot: res/data/seq/uniprot/uniprot_human_20181211.fasta
            refseq: res/data/seq/refseq/GCF_000001405.38_GRCh38.p12_protein.faa
            cnvs: res/data/seq/coding_CNVs/original_and_deleted_AAsequences_2018_11_30.fa
        tax: human
        enabled: False
    GENCODEv29:
        paths:
            crap: res/data/seq/crap/crap.fasta
            gencode: res/data/seq/gencode/gencode.v29.pc_translations.fa
        tax: human
        enabled: False
    GENCODEv27:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False
    GENCODEv27_sabido:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
            - res/data/seq/sabido/Human.DeNovo.protein
        tax: human
        enabled: False
    GENCODEv24:
        paths:
            - res/data/seq/gencode/gencode.v24.pc_translations.NoRT.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False


default_groupings:
    - single

download_path: "res/downloads/prot"
dataset_path: "res/data/prot"

samples: "samples.tsv"

datasets:
    deshmukh_2015:
        source: PRIDE
        project: PXD000288
        enabled: True
        fmt: raw
        dbs:
            - GENCODEvM27
        groupings:
            - biosample
        urls:
            pub: https://dx.doi.org/10.1074%2Fmcp.M114.044222
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD000288
    jung_2017:
        source: local
        enabled: True
        fmt: raw
        dbs:
            - GENCODEvM27
        groupings:
            - experiment
        urls:
            pub: https://doi.org/10.1074/mcp.M116.061440
            data: ftp://massive.ucsd.edu/MSV000079789
    sharma_2015:
        source: PRIDE
        project: PXD001250
        enabled: True
        fmt: raw
        dbs:
            - GENCODEvM27
        groupings:
            - experiment
        urls:
            pub: https://www.nature.com/articles/nn.4160
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD001250
    swovick_2018_mouse:
        source: PRIDE
        project: PXD007598
        enabled: True
        fmt: raw
        dbs:
            - GENCODEvM27
        groupings:
            - experiment
        urls:
            pub: https://doi.org/10.1074/mcp.RA117.000574
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD007598
    bekker_jensen_2017:
        source: PRIDE
        project: PXD004452
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv36
        groupings:
            - experiment
        urls:
            pub: https://doi.org/10.1016/j.cels.2017.05.009
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD004452
    carlyle_2017:
        source: PRIDE
        project: PXD005445
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv36
        groupings:
            - biosample
        urls:
            pub: https://doi.org/10.1038/s41593-017-0011-2
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD005445
    schiza_2019:
        source: PRIDE
        project: PXD008333
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv36
        groupings:
            - experiment
        urls:
            pub: https://doi.org/10.1074/mcp.RA118.001170
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD008333
    zhang_2014:
        source: PRIDE
        projects:
            - PXD002080
            - PXD002081
            - PXD002082
            - PXD002083
            - PXD002084
            - PXD002085
            - PXD002086
            - PXD002087
            - PXD002088
            - PXD002089
        enabled: False
        fmt: mzML
        dbs:
            - GENCODEv36
        groupings:
            - biosample
        urls:
            pub: https://doi.org/10.1038/nature13438
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD002080
    jiang_2020:
        source: PRIDE
        project: PXD016999
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv36
        groupings:
            - experiment
        urls:
            pub: https://doi.org/10.1016/j.cell.2020.08.036
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD016999
    wang_2019:
        source: PRIDE
        project: PXD010154
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv36
        groupings:
            - experiment
        urls:
            pub: https://doi.org/10.15252/msb.20188503
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD010154
    sabido:
        enabled: False
        dbs:
            - GENCODEv27
            - GENCODEv27_sabido
        groupings:
            - single
            - byrep
    wei_2016:
        urls:
            pub: https://pubs.acs.org/doi/10.1021/acs.jproteome.6b00390
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD004092
        enabled: False
        dbs:
            - GENCODEv27
    kim_2014:
        source: PRIDE
        project: PXD000561
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv36
        groupings:
            - experiment
        urls:
            pub: https://www.nature.com/articles/nature13302
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD000561
    PXD000787:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD000957:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD001242:
        enabled: False
        fmt: mgf
        dbs:
            - GENCODEv29
    PXD001581:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD002194:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD002273:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD003947:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD004092:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD004142:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD008462:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29


software:
    comet:
        param_file: res/conf/comet/comet.params.{ds}.{subset}.conf
        params:
            peptide_length_range: 7 40
        threads: 4
        enabled: True
        fmts: [cms2, ms2, mzML, mzXML]
    percolator:
        default_enzyme: trypsin
        enzymes:
            - arg-c
            - asp-n
            - chymotrypsin
            - glu-c
            - lys-c
            - lys-n
            - trypsin
        modes:
            - mix-max
            #- tdc
        pep_cutoff: 0.001
