bs:
    GENCODEv29:
        paths:
            - res/data/seq/gencode/gencode.v29.pc_translations.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False
    GENCODEv27:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False
    GENCODEv27_sabido:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
            - res/data/seq/sabido/Human.DeNovo.protein
        tax: human
        enabled: False
    GENCODEv24:
        paths: 
            - res/data/seq/gencode/gencode.v24.pc_translations.NoRT.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False

grouping_default:
    single: 'os.path.splitext(x)[0]'

datasets:
    sabido:
        enabled: False
        dbs:
            - GENCODEv27
            - GENCODEv27_sabido
        groupings:
            single: 'os.path.splitext(x)[0]'
            byrep: '"_".join(x.split("_")[0:4])'
    wei_2016:
        urls:
            pub: https://pubs.acs.org/doi/10.1021/acs.jproteome.6b00390
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD004092
        enabled: False
        dbs:
            - GENCODEv27
    kim_2014:
        enabled: True
        dbs:
            - GENCODEv27
        urls:
            pub: https://www.nature.com/articles/nature13302
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD000561
    PXD000787:
        enabled: True
        dbs:
            - GENCODEv27
    PXD000957:
        enabled: True
        dbs:
            - GENCODEv27
    PXD001242:
        enabled: True
        dbs:
            - GENCODEv27
    PXD001581:
        enabled: True
        dbs:
            - GENCODEv27
    PXD002194:
        enabled: True
        dbs:
            - GENCODEv27
    PXD002273:
        enabled: True
        dbs:
            - GENCODEv27
    PXD003947:
        enabled: True
        dbs:
            - GENCODEv27
    PXD004092:
        enabled: True
        dbs:
            - GENCODEv27
    PXD004142:
        enabled: True
        dbs:
            - GENCODEv27
    PXD008462:
        enabled: True
        dbs:
            - GENCODEv27

software:
    search:
        comet:
            params: res/conf/comet/comet.params.{ds}.conf
            threads: 4
            enabled: True
