dbs:
    GENCODEv36:
        paths:
            crud: res/data/seq/crud/crud.fasta.gz
            gencode: res/data/seq/gencode/gencode.v36.pc_translations.fa.gz
            upstream: res/data/seq/upstream/Sutured_upstream.faa.gz
        tax: human
        enabled: True
    GENCODEv33_20200420:
        paths:
            crud: res/data/seq/crud/crud.fasta
            gencode: res/data/seq/gencode/gencode.v33.pc_translations.fa
            ncx: res/data/seq/ncx/NC-xcheck.fa
        tax: human
        enabled: False
    GENCODEv33:
        paths:
            crud: res/data/seq/crud/crud.fasta
            gencode: res/data/seq/gencode/gencode.v33.pc_translations.fa
        tax: human
        enabled: False
    GUR:
        paths:
            crap: res/data/seq/crap/crap.fasta
            gencode: res/data/seq/gencode/gencode.v29.pc_translations.fa
            uniprot: res/data/seq/uniprot/uniprot_human_20181211.fasta
            refseq: res/data/seq/refseq/GCF_000001405.38_GRCh38.p12_protein.faa
            cnvs: res/data/seq/coding_CNVs/original_and_deleted_AAsequences_2018_11_30.fa
        tax: human
        enabled: False
    GENCODEv29:
        paths:
            crap: res/data/seq/crap/crap.fasta
            gencode: res/data/seq/gencode/gencode.v29.pc_translations.fa
        tax: human
        enabled: False
    GENCODEv27:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False
    GENCODEv27_sabido:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
            - res/data/seq/sabido/Human.DeNovo.protein
        tax: human
        enabled: False
    GENCODEv24:
        paths:
            - res/data/seq/gencode/gencode.v24.pc_translations.NoRT.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False


default_groupings:
    - single

dataset_path: "res/data/prot"

samples: "samples.tsv"

datasets:
    PXD010154:
        source: PRIDE
        project_accession: PXD010154
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv33
        urls:
            pub: https://doi.org/10.15252/msb.20188503
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD010154
    sabido:
        enabled: False
        dbs:
            - GENCODEv27
            - GENCODEv27_sabido
        groupings:
            - single
            - byrep
    wei_2016:
        urls:
            pub: https://pubs.acs.org/doi/10.1021/acs.jproteome.6b00390
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD004092
        enabled: False
        dbs:
            - GENCODEv27
    kim_2014:
        source: PRIDE
        project_accession: PXD000561
        enabled: True
        fmt: raw
        dbs:
            - GENCODEv33_20200420
        urls:
            pub: https://www.nature.com/articles/nature13302
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD000561
    PXD000787:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD000957:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD001242:
        enabled: False
        fmt: mgf
        dbs:
            - GENCODEv29
    PXD001581:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD002194:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD002273:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD003947:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD004092:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD004142:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD008462:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29


rules:
    msconvert:
        output:
            flags: [temp]
    download_sample:
        output:
            flags: [temp]


software:
    comet:
        params: res/conf/comet/comet.params.{ds}.{subset}.conf
        threads: 4
        enabled: True
        fmts: [cms2, ms2, mzML, mzXML]
    msconvert:
        docker_image: chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:latest

        # Set Docker host to 'local' to run msconvert on the same machine as the
        # main workflow; set to 'remote' to convert files on a different machine.
        docker_host: local

        # For 'remote' mode only: configure SSH connection
        # from local machine to remote host, and vice versa.
        local:
            # User and host name for local host.
            hostname: local_host
            username: local_user

            # Path of private key file on local host,
            # used to connect to the remote host.
            private_key: /home/local_user/.ssh/id_rsa
        remote:
            # User and host name for local host.
            hostname: remote_host
            username: remote_user

            # Path of private key file on the remote
            # host, used to connect to the local host.
            private_key: /home/remote_user/.ssh/id_rsa

        fmts: [raw]
    percolator:
        default_enzyme: trypsin
        enzymes:
            - arg-c
            - asp-n
            - chymotrypsin
            - glu-c
            - lys-c
            - lys-n
            - trypsin
        modes:
            - mix-max
            #- tdc
        pep_cutoff: 0.001
