dbs:
    GENCODEv33:
        paths:
            crud: res/data/seq/crud/crud.fasta
            gencode: res/data/seq/gencode/gencode.v33.pc_translations.fa
        tax: human
        enabled: True
    GUR:
        paths:
            crap: res/data/seq/crap/crap.fasta
            gencode: res/data/seq/gencode/gencode.v29.pc_translations.fa
            uniprot: res/data/seq/uniprot/uniprot_human_20181211.fasta
            refseq: res/data/seq/refseq/GCF_000001405.38_GRCh38.p12_protein.faa
            cnvs: res/data/seq/coding_CNVs/original_and_deleted_AAsequences_2018_11_30.fa
        tax: human
        enabled: False
    GENCODEv29:
        paths:
            crap: res/data/seq/crap/crap.fasta
            gencode: res/data/seq/gencode/gencode.v29.pc_translations.fa
        tax: human
        enabled: False
    GENCODEv27:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False
    GENCODEv27_sabido:
        paths:
            - res/data/seq/gencode/gencode.v27.pc_translations.fa
            - res/data/seq/crap/crap.fasta
            - res/data/seq/sabido/Human.DeNovo.protein
        tax: human
        enabled: False
    GENCODEv24:
        paths:
            - res/data/seq/gencode/gencode.v24.pc_translations.NoRT.fa
            - res/data/seq/crap/crap.fasta
        tax: human
        enabled: False

grouping_default:
    single: 'split_gzip_ext(x)[0]'

dataset_path: "res/data/prot"

datasets:
    PXD010154:
        source: PRIDE
        project_accession: PXD010154
        enabled: True
        fmt: raw
        dbs:
            - GENCODEv33
        urls:
            pub: https://doi.org/10.15252/msb.20188503
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD010154
        subsets:
            trypsin:
                samples: res/conf/subsets/PXD010154/trypsin.txt
    sabido:
        enabled: False
        dbs:
            - GENCODEv27
            - GENCODEv27_sabido
        groupings:
            single: 'os.path.splitext(x)[0]'
            byrep: '"_".join(x.split("_")[0:4])'
    wei_2016:
        urls:
            pub: https://pubs.acs.org/doi/10.1021/acs.jproteome.6b00390
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD004092
        enabled: False
        dbs:
            - GENCODEv27
    kim_2014:
        enabled: False
        fmt: mzML
        dbs:
            - GUR
        urls:
            pub: https://www.nature.com/articles/nature13302
            data: https://www.ebi.ac.uk/pride/archive/projects/PXD000561
    PXD000787:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD000957:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD001242:
        enabled: False
        fmt: mgf
        dbs:
            - GENCODEv29
    PXD001581:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD002194:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD002273:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD003947:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD004092:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD004142:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29
    PXD008462:
        enabled: False
        fmt: raw
        dbs:
            - GENCODEv29

software:
    comet:
        params: res/conf/comet/comet.params.{ds}.{subset}.conf
        threads: 4
        enabled: True
        fmts: [cms2, ms2, mzML, mzXML]
    msconvert:
        docker_image: chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:latest
        local:
            hostname: local_host
            username: local_user
            private_key: /home/local_user/.ssh/id_rsa
        remote:
            hostname: remote_host
            username: remote_user
            private_key: /home/remote_user/.ssh/id_rsa
        fmts: [raw]
    percolator:
        modes:
            - mix-max
            #- tdc
