name: prot
channels:
    - bioconda
    - conda-forge
    - defaults
    - http://conda.anaconda.org/tdido
dependencies:
    - snakemake
    - proteowizard
    - tstk
    - lxml

    #for Xtandem .xml to pep.xml conversion also pip install pyteomics pyteomics.pepxmltk
